name: Proteth
favicon: null
layout_spectrum: 0.11198
typography_spectrum: 0.81503
title: Proteth - Protection from the ill-effects of alcohol
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#da0037'
    - '#000000'
    - '#255195'
    - '#eda89b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.16714270925149322
  rhythmicContrast: 0.5
purpose: []
