name: Proteth
favicon: null
layout_spectrum: 0.5483
typography_spectrum: 0.81503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#da0037'
    - '#000000'
    - '#255195'
    - '#eda89b'
  brandStrength: 0.125
  lightness: 0.13740358385257423
  saturation: 0.16714270925149322
  rhythmicContrast: 0.38299033255316317
purpose: []
